### ISSUE TITLE
mdg-tool dumps on sparx XMI fails with AttributeError: 'tuple' object has no attribute 'Meta'

### ISSUE THREAD

**Issue by Semprini** [Semprini/pyMDG#41]
Works for drawio though,

mdg-tool dumps sample_recipes\config-sparx-docs.yaml
2022-08-08 10:49:54,753 | mdg.config | INFO | Config file loaded: sample_recipes\config-sparx-docs.yaml
2022-08-08 10:49:54,802 | mdg.parse.sparx_xmi | INFO | Parsing models
2022-08-08 10:49:54,825 | mdg.parse.sparx_xmi | INFO | Parsing test cases
2022-08-08 10:49:54,828 | mdg.parse | INFO | Base Model Package: SampleIndustry
Traceback (most recent call last):
  File "C:\Dev\python\pyMDG-master\mdg-tool.py", line 6, in <module>
    main()
  File "C:\Dev\python\pyMDG-master\mdg\tools\mdg_tool.py", line 77, in main
    func(args)
  File "C:\Dev\python\pyMDG-master\mdg\tools\mdg_tool.py", line 36, in dumps
    print(dumps(model_package))
  File "C:\Dev\python\pyMDG-master\mdg\uml\__init__.py", line 368, in dumps
    output = obj_to_dict(package)
  File "C:\Dev\python\pyMDG-master\mdg\tools\io.py", line 38, in obj_to_dict
    new_value.append(obj_to_dict(element))
  File "C:\Dev\python\pyMDG-master\mdg\tools\io.py", line 38, in obj_to_dict
    new_value.append(obj_to_dict(element))
  File "C:\Dev\python\pyMDG-master\mdg\tools\io.py", line 28, in obj_to_dict
    value = getattr(value, value.Meta.id_field)
AttributeError: 'tuple' object has no attribute 'Meta'

**Comment by Semprini** [comment]
Oops false alarm, was working with old code.
